# Generated by Django 2.2.1 on 2019-05-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercise_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='workout_diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(auto_now=True)),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('notes', models.CharField(max_length=256)),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weights.exercise_list')),
            ],
        ),
    ]
