# Generated by Django 2.2.1 on 2019-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weights', '0002_auto_20190514_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='muscles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_worked', models.CharField(max_length=256)),
            ],
        ),
    ]
