# Generated by Django 2.2.1 on 2019-05-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Weights', '0003_muscles'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_list',
            name='muscle_worked',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='Weights.muscles'),
            preserve_default=False,
        ),
    ]
