# Generated by Django 2.2.1 on 2019-05-19 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weights', '0008_auto_20190518_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_diary',
            name='workout_date',
            field=models.DateField(default=datetime.date(2019, 5, 19)),
        ),
    ]
