# Generated by Django 2.2.1 on 2019-05-23 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weights', '0009_auto_20190519_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_diary',
            name='workout_date',
            field=models.DateField(default=datetime.date(2019, 5, 23)),
        ),
    ]
