# Generated by Django 2.2.2 on 2019-06-12 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weights', '0011_auto_20190609_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='age',
        ),
        migrations.AlterField(
            model_name='workout_diary',
            name='workout_date',
            field=models.DateField(default=datetime.date(2019, 6, 12)),
        ),
    ]
