# Generated by Django 2.2.2 on 2019-06-14 07:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Weights', '0012_auto_20190612_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_diary',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout_diary',
            name='workout_date',
            field=models.DateField(default=datetime.date(2019, 6, 14)),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
